#+TITLE: ?

#+DATE: Mai 2017
#+AUTHOR: Basile Pillet

#+LATEX_CLASS: amsdip
#+LATEX_CLASS_OPTIONS: [a4paper]

#+LATEX_HEADER: \newtheorem{thm}{Théorème}

#+STARTUP: indent

* Plan

*** Contexte
On se fixe une variété complexe $Z$ fibrée sur $\Pro^1$.

On fait $2$ hypothèses :
- Il y a des sections particulières (verticales)
  Une par chaque point.
- Si $L$ est l'image d'une section de $f : Z \to \Pro^1$ (droite), alors 
  $N_{L/Z}$ est une somme de $\Oo(1)$.
  En particulier $H^1(L,N_{L/Z}) = 0$ et donc dans toutes les directions cette section se déforme.\\
  Les droites de $Z$ peuvent se déformer dans $Z$.

En particulier $Z$ est une variété rationnellement connexe.

*** EG
- Espace des twisteurs d'une surface K3 (ou var HK), 
- Espace total de $\Oo(1) \oplus \Oo(1)$,


** Théorie des Épaississements
Point de vu GA : définir un objet géométrique c'est définir les fonctions dessus. On veut définir ce que sont les *voisinages infinitésimaux d'une droite dans $Z$*

La droite $L$ est représentée par son faisceau de fonctions $\Oo_L$ qui est lié aux fonctions sur $Z$ par la suite exacte
\[
0 \to \Ii_L \to \Oo_Z \to i_* \Oo_L \to 0
\]
où $i : L \hookrightarrow Z$ et $\Ii_L$ l'idéal des fonctions sur $Z$ qui s'annulent sur $L$.

C'est-à-dire : Une fonction sur $L$ provient d'une fonction sur $Z$ modulo les fonctions qui s'annulent sur $L$. (où tout est à comprendre au sens "local")

*** Épaississement
Il suffit de définir $\Oo_L^{(n)}$ le faisceau des fonctions
\[
0 \to \Ii^{n+1}_L \to \Oo_Z \to i_* \Oo_L^{(n)} \to 0
\]
sur $Z$ modulo celles qui s'annulent à l'ordre $n+1$ sur $L$.

La /variété épaissie/ $L^{(n)}$ est alors l'espace topologique $L$ mais possédant beaucoup plus de fonctions : $\Oo^{(n)}_L$.

Une fonction sur $L^{(n)}$ est un jet d'ordre $n$ de fonctions sur $L$.

:TODO:
Lien avec les vecteurs tangents ; exemples
:END:

**** Droite dans $\Pro^3$
Considérons $\Pro^3$ avec coordonnées homogènes $[X_0:X_1:X_2:X_3]$ et définissons $L$ la droite d'équation $X_1=X_2= 0$. Le faisceau $\Ii_L$ est localement engendré par
- $x = X_1/X_0$ et $y = X_2/X_0$ sur $U_0$
- $u = X_1/X_3$ et $v = X_2/X_3$ sur $U_3$
Les coordonnées associées sur $L$ sont données par
- $z = X_3/X_0$ sur $U_0$
- $w = X_0/X_3$ sur $U_3$

Ainsi sur $U_0$, un germe de fonction qui s'annule sur $L$ s'écrit (pas forcément de manière unique)
\[
xf(x,y,z) + yg(x,y,z)
\]
et un germe de $\Ii^n$
\[
x^nf_n(x,y,z) + x^{n-1}yf_{n-1}(x,y,z) + \cdots + y^nf_0(x,y,z)
\]

Par exemple $x \in \Oo_{\Pro^3}\vert U_0$ donne par restriction à $L$ la fonction nulle sur $L \cap U_0$, mais définit une fonction locale non-nulle sur $L^{(1)}$ ; cette fonction $\chi$ vérifie $\chi^2 = 0$. (On peut la voir comme un $\dd x$, ou un $\varepsilon$ quand on néglige les termes d'ordre $2$).

*** Épaississement de fibrés

Avec les notations du paragraphe précédent, soit $E \to X$ un fibré vectoriel. On appelle épaississement de $E$ à l’ordre $m$ sur $X^{(m)}$ un faisceau localement libre $\Ff$ de \(\Oo_X\)-modules tel que
\[
\Oo_X \otimes_{\Oo^{(m)}} \Ff \simeq \Oo_X(E)
\]
c’est-à-dire il étend le fibré $E$ sur $X$ à $X^{(m)}$.

On note $\Ff = \Oo_X^{(m)}(E^{(m)})$.

C'est le faisceau des sections sur $X^{(m)}$ d'un "fibré vectoriel". Si on se restreint aux sections obtenues avec des vrais fonctions locales de $L$, on retrouve $E$.


*** Épaississements de connexions
Là ça devient plus complexe !

Rappel : L'existence d'une connexion $\nabla$ sur un faisceau cohérent $\Ff$ entraîne que $\Ff$ est localement libre. [Malgrange]

https://justinsmath.wordpress.com/2012/05/30/a-coherent-sheaf-with-connection-is-locally-free/

Une connexion sur un faisceau *rigidifie* le faisceau. Dans notre contexte : Soit $\nabla^{(m)}$ une connexion sur $E^{(m)}$. Alors elle définit de manière unique un épaississement $E^{(m+1)}$ de $E^{(m)}$ !

Ainsi épaissir les fibrés à connexion est un ping-pong entre d’une part l’épaississement de la connexion sur un fibré fixé et d’autre part le choix de l’épaississement du fibré. Il y a des obstruction à chaque cran qu'il faut gérer.

**** Exemple ?



** Correspondance de Buchdahl

On s'intéresse aux voisinages infinitésimaux d'une droite dans $Z$. 

*** Espace des sections et correspondance twistorielle
 Soit $C$ l'espace des sections de $Z$ (espace de Douady, espace des cycles de Barlett).

\[
(T_C)_s \simeq H^0(L_s, N_{L_s/Z})
\]
Mais comme le $H^1$ s'annule

(( à finir ))

*** EG

Grassmanienne des $2$ -plans privée d'un point et d'un $\Pro^1$.

*** Fibré L-triviaux

*** Fibré à connexion associé

*** EQV catégorie
On a le théorème
#+BEGIN_thm
Il y a une équivalence de catégories
\begin{equation*}
\left\lbrace
\begin{matrix}
\text{Fibré à connexion sur }C \\
+ \text{ restriction de courbure}
\end{matrix}
\right\rbrace \quad \leftrightarrow \quad \left\lbrace
\begin{matrix}
\text{Fibré vectoriel holomorphe sur }Z\\
+ \text{ trivial sur les droites}
\end{matrix}
\right\rbrace
\end{equation*}
#+END_thm

** Relation épaississement-courbure

*** Théorème
On a le théorème
#+BEGIN_thm
L'équivalence précédente se restreint à
\begin{equation*}
\left\lbrace
\begin{matrix}
\text{Fibré à connexion}\\
\textbf{plate} \text{ sur } C
\end{matrix}
\right\rbrace \quad \leftrightarrow \quad \left\lbrace
\begin{matrix}
\text{Fibré holomorphe sur }Z\\
\text{trivial sur les voisinages}\\
\text{infinitésimaux des droites à l'ordre }2
\end{matrix}
\right\rbrace.
\end{equation*}
#+END_thm

*** Idée de la preuve ?



** Applications

* Idées
- Épaississements ; correspondance de Buchdahl ; courbure
* Références 
- Buchdahl


