#+TITLE: ?

#+AUTHOR: Basile Pillet
#+DATE: Mai 2017

* Plan

*** Contexte
On se fixe une variété complexe $Z$ fibrée sur $\Pro^1$.

On fait $2$ hypothèses :
- Il y a des sections particulières (verticales)
  Une par chaque point.
- Si $L$ est l'image d'une section de $f : Z \to \Pro^1$ (droite), alors 
  $N_{L/Z}$ est une somme de $\Oo(1)$.
  En particulier $H^1(L,N_{L/Z}) = 0$ et donc dans toutes les directions cette section se déforme.\\
  Les droites de $Z$ peuvent se déformer dans $Z$.

En particulier $Z$ est une variété rationnellement connexe.

*** EG
- Espace des twisteurs d'une surface K3 (ou var HK), 
- Espace total de $\Oo(1) \oplus \Oo(1)$,


** Épaississements
Point de vu GA : définir un objet géométrique c'est définir les fonctions dessus. On veut définir ce que sont les *voisinages infinitésimaux d'une droite dans $Z$*

La droite $L$ est représentée par son faisceau de fonctions $\Oo_L$ qui est lié aux fonctions sur $Z$ par la suite exacte
\[
0 \to \Ii_L \to \Oo_Z \to i_* \Oo_L \to 0
\]
où $i : L \hookrightarrow Z$ et $\Ii_L$ l'idéal des fonctions sur $Z$ qui s'annulent sur $L$.

C'est-à-dire : Une fonction sur $L$ provient d'une fonction sur $Z$ modulo les fonctions qui s'annulent sur $L$. (où tout est à comprendre au sens "local")

*** Épaississement
Il suffit de définir $\Oo_L^{(n)}$ le faisceau des fonctions
\[
0 \to \Ii^{n+1}_L \to \Oo_Z \to i_* \Oo_L^{(n)} \to 0
\]
sur $Z$ modulo celles qui s'annulent à l'ordre $n+1$ sur $L$.

La /variété épaissie/ $L^{(n)}$ est alors l'espace topologique $L$ mais possédant beaucoup plus de fonctions : $\Oo^{(n)}_L$.

Une fonction sur $L^{(n)}$ est un jet d'ordre $n$ de fonctions sur $L$.

:TODO:
Lien avec les vecteurs tangents ; exemples
:END:












** Correspondance de Buchdahl

On s'intéresse aux voisinages infinitésimaux d'une droite dans $Z$. 

*** Espace des sections et correspondance twistorielle
 Soit $C$ l'espace des sections de $Z$ (espace de Douady, espace des cycles de Barlett).

\[
(T_C)_s \simeq H^0(L_s, N_{L_s/Z})
\]
Mais comme le $H^1$ s'annule

(( à finir ))

*** EG

Grassmanienne des $2$ -plans privée d'un point et d'un $\Pro^1$.

*** Fibré \(L\)-triviaux

*** Fibré à connexion associé

*** EQV catégorie

** Épaississements

*** Théorème


** Applications

* Idées
- Épaississements ; correspondance de Buchdahl ; courbure
* Références 
- Buchdahl


